name = "ClimaViz"
uuid = "9706fb73-1de9-418d-83da-fef8cd99bb4a"
authors = ["AlexisRenchon <a.renchon@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.10"
